sudo: false

cache:
  directories:
  - $HOME/.m2/repository
  - $HOME/.sbt
  - $HOME/.ivy2

language: scala

scala:
- 2.10.5
- 2.11.7

jdk:
- oraclejdk7

sbt_args: -no-colors -J-Xss2m

script: sbt ++$TRAVIS_SCALA_VERSION -Dsbt.log.noformat=true test

notifications:
  email:
  - seth.yates@krux.com
  - kxie@krux.com
  - ysalomon@krux.com

before_install:
- |
  if [[ "${TRAVIS_BRANCH}" == "master" && "${TRAVIS_PULL_REQUEST}" = "false" ]]; then
    openssl aes-256-cbc -K $encrypted_eb2e0c1b1c49_key -iv $encrypted_eb2e0c1b1c49_iv -in secring.asc.enc -out secring.asc -d
    openssl aes-256-cbc -K $encrypted_eb2e0c1b1c49_key -iv $encrypted_eb2e0c1b1c49_iv -in pubring.asc.enc -out pubring.asc -d
  fi

after_success:
- |
  if [[ "${TRAVIS_BRANCH}" == "master" && "${TRAVIS_PULL_REQUEST}" = "false" ]]; then
    sbt ++$TRAVIS_SCALA_VERSION 'set pgpPassphrase := Some(System.getenv("PGP_PASSPHRASE").toCharArray)' 'set credentials += Credentials("Sonatype Nexus Repository Manager", "oss.sonatype.org", System.getenv("SONATYPE_USERNAME"), System.getenv("SONATYPE_PASSWORD"))' publishSigned sonatypeReleaseAll
    rm -f secring.asc pubring.asc
  fi

env:
  global:
  - secure: P0hN/qmlzFkcVZ63zQHQymkFpcIpaWCGs7vbXiVHyvc5xqswtCQuy1C2jQDQc2r9J4/VkUgbXNAIYAraRmyGix7+27f314Nuk44k5s7xsuXvs3NN3RqK0r6Mkirn4oV/ZOhiHUseFWw3KP91ifFUUbE0b1f+xOtRN8uPhT4It8k=
  - secure: b/XcN+JB6b+ajlIjnRGGFzArJRTKXkxuUE+NjUOLsjd9O9EP3Ap4E3PObYW5iUd+8AE2nBwql8BJYFgLJv1xvy0r+jbtRCL15pmeQtcNyfPVSWsZlpJIF1DNeRF+TzMTpYSbldMQM4YyQVv8/gzkEZ3MQ8+tWNXCFPa35VP6bUY=
  - secure: GDEME7KE6jFcp6Ktv5gJY0rUbDVzz7uV5JhR2hk+aBy1F0HnWDLXk5d/6an4RjIJ2cOGcPs8YEApo6viuc12dHcwhFTRWQH1DZqUI9F1mi1TZ4HGHQclpGhJud2Jr0Inwcm2D8lhe7FHbspAzeVkUBRhW7qiNsM9iQfgZ8qZQAE=

